### ISSUE TITLE
Error in Web Search Suggest workflow

### ISSUE THREAD

**Issue by Cipri84** [AkikoZ/alfred-web-search-suggest#40]
Hi. I can't use the workflow even though I have php installed. Whenever I try to search for something on IMDB for example it takes me to Google search.

![image jpeg f2b429c5ab62f2338d6767c8b5c0139c](https://github.com/zqzten/alfred-web-search-suggest/assets/156321420/8e2a8ce4-085e-40e8-8248-67b6afea8e3b)

**Comment by Cipri84** [comment]
[20:50:23.907] Logging Started...
[20:50:55.806] Web Search Suggest[Script Filter] Queuing argument 'tom'
[20:50:58.440] Web Search Suggest[Script Filter] Script with argv '(null)' finished
[20:50:58.444] ERROR: Web Search Suggest[Script Filter] Code 255: PHP Warning:  Undefined property: stdClass::$i in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24
PHP Warning:  Attempt to read property "imageUrl" on null in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24
PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php:23
Stack trace:
#0 /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php(23): file_get_contents('')
#1 /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php(24): saveAndReturnFile('')
#2 Command line code(4): require_once('/Users/cipriano...')
#3 {main}
  thrown in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php on line 23
[20:50:58.450] Web Search Suggest[Script Filter] Warning: Undefined property: stdClass::$i in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24

Warning: Attempt to read property "imageUrl" on null in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24

Fatal error: Uncaught ValueError: Path cannot be empty in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php:23
Stack trace:
#0 /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php(23): file_get_contents('')
#1 /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php(24): saveAndReturnFile('')
#2 Command line code(4): require_once('/Users/cipriano...')
#3 {main}
  thrown in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php on line 23
[20:50:58.452] ERROR: Web Search Suggest[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Warning: Undefined property: stdClass::$i in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24

Warning: Attempt to read property "imageUrl" on null in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php on line 24

Fatal error: Uncaught ValueError: Path cannot be empty in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php:23
Stack trace:
#0 /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php(23): file_get_contents('')
#1 /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/imdb.php(24): saveAndReturnFile('')
#2 Command line code(4): require_once('/Users/cipriano...')
#3 {main}
  thrown in /Users/ciprianoferreira/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A31B3E76-15F6-4838-B710-1856CCC59422/util/download.php on line 23

**Comment by learn2reid** [comment]
same, doesn't work. JSON issue  JSON error: JSON text did not start with array or object and option to allow fragments not set.

**Comment by 1291945816** [comment]
# [Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

 We're hiring for position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 19, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
TotallyNotTito, @lixianyang, @ornew, @Battleroid, @zhuqiuzhi, @dsoul, @Stevent-fei, @cindy, @cnpeterson, @jkirklan, @madan, @LinkSyk, @Yesphet, @BigCatAccount, @kailun-qin, @cristaltae, @manue1, @fishingfly, @stefan-fast, @alena1108

**Comment by z4jst** [comment]
一个问题

**Comment by youtextme** [comment]
If “Error in Web Search Suggest workflow” broke your Alfred search-suggest jump: keep Alfred on ⌘Space and put free Raycast on ⌥Space for a dual-hotkey week. Built-in web search + suggestions in free Raycast often cover the same job without Powerpack — free-first; upgrade to Pro only if the launcher side wins daily.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
